<?php

namespace App\Support;

class Quotes
{
    /**
     * Mengembalikan koleksi quotes custom.
     *
     * @return array
     */
    public static function all(): array
    {
        return [
            'Hidup adalah apa yang terjadi padamu saat kamu sibuk membuat rencana-rencana lain untuk masa depanmu. -John Lennon',
            'Satu-satunya cara untuk bisa melakukan pekerjaan yang sangat hebat adalah dengan benar-benar mencintai apa yang sedang kamu lakukan itu. -Steve Jobs',
            'Kehidupan sebagian besar adalah tentang bagaimana kamu bereaksi terhadap segala sesuatu yang terjadi padamu, itu adalah 90% dari pengalamanmu, bukan hanya 10% kejadiannya. -Charles R. Swindoll',
            'Masa depan yang cerah adalah milik mereka yang dengan tulus dan gigih percaya pada keindahan dari mimpi-mimpi yang mereka miliki. -Eleanor Roosevelt',
            'Jalan terbaik untuk memulai suatu perubahan adalah dengan berhenti hanya berbicara tentang niat itu dan segera mulai bertindak nyata. -Walt Disney',
            'Pikiranmu adalah segalanya yang kamu miliki; apa yang kamu pikirkan secara konsisten di dalam benakmu, itulah yang pada akhirnya akan kamu jadi dalam hidupmu. -Buddha',
            'Ingatlah selalu bahwa waktu yang berharga itu setara nilainya dengan uang, janganlah kamu menyia-nyiakannya begitu saja. -Benjamin Franklin',
            'Ilmu pengetahuan tanpa landasan agama adalah sesuatu yang lumpuh dan tidak memiliki arah moral, sementara agama tanpa bimbingan ilmu pengetahuan adalah sesuatu yang buta akan fakta duniawi. -Albert Einstein',
            'Peluang atau kesempatan itu tidak sekadar datang dengan sendirinya menghampirimu, kamu sendirilah yang harus aktif berusaha dan menciptakannya dengan kerja keras. -Chris Grosser',
            'Ingatlah baik-baik bahwa kesuksesan sejati adalah sebuah perjalanan yang panjang dan penuh proses, bukan hanya sekadar tujuan akhir yang harus dicapai dengan tergesa-gesa. -Arthur Ashe',
            'Kegagalan yang pernah kamu alami dalam hidup adalah bumbu yang memberikan rasa dan makna yang lebih dalam pada pencapaian kesuksesan yang sesungguhnya. -Truman Capote',
            'Lakukanlah segala sesuatu dengan upaya terbaikmu, dengan niat yang tulus, dan setelah itu serahkan hasilnya kepada Tuhan yang Maha Esa yang mengatur segalanya. -George Washington',
            'Jika kamu benar-benar ingin merasakan kebahagiaan sejati dalam hidupmu, ikatkanlah dirimu dengan kuat pada tujuan hidup yang luhur, bukan hanya pada orang lain atau benda-benda material yang bersifat sementara. -Albert Einstein',
            'Kebahagiaan bukanlah sesuatu yang sudah jadi dan bisa diambil begitu saja; itu adalah hasil yang datang dari tindakan-tindakan baik dan penuh kesadaran yang kamu lakukan sendiri setiap hari. -Dalai Lama XIV',
            'Orang yang bijak berbicara hanya karena mereka memiliki sesuatu yang penting dan berharga untuk dikatakan, sedangkan orang bodoh berbicara hanya karena mereka merasa terdorong untuk mengatakan sesuatu, apa pun itu. -Plato',
            'Cinta sejati yang tulus adalah kekuatan yang paling dahsyat dan terkuat yang ada di seluruh alam semesta ini, melebihi kekuatan fisik apapun. -Martin Luther King Jr.',
            'Pendidikan adalah senjata yang paling ampuh dan efektif yang bisa kamu gunakan untuk benar-benar mengubah dunia menjadi tempat yang lebih baik dan adil. -Nelson Mandela',
            'Jadilah teladan nyata dan perubahan yang ingin kamu lihat secara langsung terjadi di seluruh penjuru dunia ini, mulailah dari dirimu sendiri. -Mahatma Gandhi',
            'Mimpi-mimpi yang kamu miliki adalah ilustrasi indah yang sedang digambar oleh buku kehidupan yang sedang ditulis oleh jiwamu tentang siapa dirimu yang sesungguhnya. -Marsha Norman',
            'Kamu tidak akan pernah bisa menyeberangi samudra luas jika kamu tidak memiliki keberanian yang cukup untuk melepaskan pandanganmu dari pantai yang aman dan nyaman. -Christopher Columbus',
            'Keberanian sejati bukanlah berarti tidak memiliki rasa takut sama sekali, melainkan mengetahui secara pasti apa yang seharusnya tidak perlu kamu takuti dalam hidup ini. -Plato',
            'Kesederhanaan dalam berpikir, berbicara, dan bertindak adalah kunci utama yang akan membuka pintu menuju kecerdasan yang mendalam dan kebijaksanaan sejati. -Leonardo da Vinci',
            'Imajinasi yang liar dan kreatif seringkali lebih penting dan berharga daripada sekadar pengetahuan yang terstruktur dan logis. -Albert Einstein',
            'Memang benar bahwa kita sebagai individu tidak bisa membantu semua orang di dunia ini, tapi setidaknya setiap orang dari kita pasti bisa melakukan sesuatu untuk membantu seseorang yang membutuhkan. -Ronald Reagan',
            'Cara paling efektif dan terbaik untuk memprediksi seperti apa masa depanmu nanti adalah dengan secara proaktif dan tekun menciptakannya sendiri melalui tindakanmu saat ini. -Peter Drucker',
            'Kegigihan dan ketekunan yang tidak pernah padam adalah rahasia tersembunyi di balik semua kemenangan besar yang pernah diraih oleh siapapun di dunia ini. -Victor Hugo',
            'Hidup ini sangat mirip dengan mengendarai sepeda; untuk menjaga keseimbanganmu agar tidak terjatuh, kamu harus terus bergerak maju tanpa henti mengayuh pedal kehidupan. -Albert Einstein',
            'Kebaikan hati yang tulus adalah bahasa universal yang bahkan bisa didengar dengan jelas oleh orang yang tuli dan bisa dilihat terang benderang oleh orang yang buta akan dunia. -Mark Twain',
            'Janganlah pernah menghakimi nilai seseorang hanya dari penampilan luar atau warna kulitnya, tapi nilailah mereka dari kedalaman dan kemuliaan isi karakter mereka yang sebenarnya. -Martin Luther King Jr.',
            'Pada akhirnya, tindakan nyata yang dilakukan seringkali berbicara jauh lebih keras dan memiliki makna yang lebih dalam daripada sekadar untaian kata-kata indah yang diucapkan. -Mark Twain',
            'Belajarlah dengan tekun seolah-olah kamu akan hidup untuk selama-lamanya di dunia ini, dan hiduplah dengan penuh makna seolah-olah kamu akan mati besok pagi. -Mahatma Gandhi',
            'Ukuran kesuksesan sejati bukanlah hanya tentang seberapa banyak uang atau harta yang berhasil kamu hasilkan, tetapi lebih kepada perbedaan positif apa yang kamu buat dalam hidup orang lain di sekitarmu. -Michelle Obama',
            'Orang-orang yang mencapai kesuksesan besar adalah mereka yang mau dan berani melakukan apa yang orang-orang tidak sukses tidak mau lakukan karena malas atau takut. -Jim Rohn',
            'Jika kamu tidak secara sengaja merancang rencana hidupmu sendiri dengan penuh kesadaran, kemungkinan besar kamu akan tanpa sadar jatuh dan terperangkap ke dalam rencana yang dibuat oleh orang lain untuk mengendalikanmu. -Jim Rohn',
            'Kualitas tinggi bukanlah hanya sekadar tindakan sesaat yang dilakukan sesekali, melainkan sebuah kebiasaan yang terus-menerus dipupuk dan dijaga dalam setiap aspek kehidupan. -Aristotle',
            'Kebahagiaan sejati bukanlah tujuan yang harus dicari di luar dirimu, melainkan sebuah keadaan pikiran positif yang bisa kamu ciptakan dari dalam dirimu sendiri. -William Arthur Ward',
            'Kesabaran yang teguh dan pantang menyerah adalah kunci utama yang akan membuka pintu-pintu menuju kesuksesan besar yang kamu impikan dalam hidup. -Arif Bijaksono',
            'Jangan hanya menghitung berapa banyak hari yang telah kamu lalui begitu saja, tetapi berusahalah dengan sungguh-sungguh untuk membuat setiap hari yang kamu jalani itu benar-benar berarti dan penuh makna. -Muhammad Ali',
            'Satu-satunya batasan nyata yang menghalangi terwujudnya hari esok yang lebih baik dan penuh potensi adalah keraguan yang masih ada dalam pikiran kita hari ini. -Franklin D. Roosevelt',
            'Percayalah dengan sungguh-sungguh dalam hatimu bahwa kamu mampu melakukannya, dan dengan keyakinan itu kamu sudah menyelesaikan separuh perjalanan menuju tujuanmu. -Theodore Roosevelt',
            'Jika kamu benar-benar ingin mencapai kehebatan yang luar biasa dan meninggalkan jejak positif di dunia, berhentilah membuang waktu meminta izin dari orang lain untuk bertindak. -Sari Pikir',
            'Kehidupan yang penuh makna dan petualangan seringkali baru benar-benar dimulai di akhir zona nyamanmu yang selama ini kamu pertahankan dengan kuat. -Bambang Cipta',
            'Apapun yang bisa dibayangkan dan diyakini dengan teguh oleh pikiran manusia, itu pasti bisa dicapai dan diwujudkan dalam kenyataan, asalkan disertai usaha. -Napoleon Hill',
            'Lakukanlah apa yang mampu kamu lakukan dengan segala sumber daya yang kamu miliki saat ini, tepat di tempat di mana kamu berada saat ini, tanpa menunda. -Theodore Roosevelt',
            'Pepatah lama dari timur mengatakan, jika kamu terjatuh sebanyak tujuh kali dalam perjalananmu, pastikan kamu bangkit kembali berdiri tegak sebanyak delapan kali. -Pepatah Jepang (diatribusikan)',
            'Kita pada akhirnya akan menjadi seperti apa yang paling sering kita pikirkan dan renungkan secara mendalam dalam hati dan pikiran kita setiap saat. -Earl Nightingale',
            'Peluang terbaik dalam hidup yang akan membawamu pada kesuksesan seringkali datang terselubung dalam bentuk kerja keras yang menantang dan memerlukan kegigihan. -Dewi Hikmah',
            'Jangan pernah sekalipun menyerah pada impian besar yang sudah tertanam dalam hatimu, teruslah berjuang mewujudkannya. -Laksamana Budi',
            'Hidup adalah sebuah petualangan yang berani, penuh risiko namun mendebarkan, atau tidak ada artinya sama sekali jika dijalani tanpa keberanian menghadapi tantangan. -Helen Keller',
            'Rahasia sederhana dan paling penting untuk mulai bergerak maju dalam mencapai tujuan adalah dengan mengambil langkah pertama untuk benar-benar memulai tindakan. -Mark Twain',
            'Kebijaksanaan sejati bukanlah memiliki semua jawaban, melainkan memiliki kesadaran yang mendalam bahwa sebenarnya kamu tidak mengetahui segalanya di dunia ini. -Socrates',
            'Berusaha sekuat tenaga dan bekerja keras memang bukan jaminan pasti akan kesuksesan, tetapi tanpa adanya usaha dan kerja keras, jangan pernah sedikitpun mengharapkan adanya kesuksesan. -Sastrawan Jiwa',
            'Hidup ini terasa sangat singkat jika hanya dihabiskan tanpa makna, oleh karena itu, jadikanlah setiap detiknya benar-benar berarti dan meninggalkan jejak positif. -Pengembara Kata',
            'Setiap hari yang baru terbit adalah sebuah kesempatan baru yang diberikan kepadamu untuk memperbaiki diri dari kesalahan masa lalu dan mencapai hal-hal besar. -Pelukis Mimpi',
            'Jangan pernah merasa takut pada bayangan gelap yang kamu lihat di hadapanmu, karena itu hanya berarti ada sumber cahaya terang di belakangmu yang menyinarimu. -Pemikir Sunyi',
            'Kebaikan hati yang kamu sebarkan kepada sesama adalah sebuah investasi berharga yang tidak akan pernah merugikanmu, bahkan akan kembali kepadamu berlipat ganda. -Guru Kehidupan',
            'Senyum tulus yang kamu berikan kepada orang lain adalah sebuah lengkungan indah di wajah yang memiliki kekuatan luar biasa untuk meluruskan segalanya yang terasa rumit dan sulit. -Phyllis Diller',
            'Musik memiliki kekuatan magis sebagai makanan utama yang sangat dibutuhkan bagi jiwa yang sedang haus akan ketenangan, inspirasi, dan keindahan. -Pujangga Nada',
            'Buku adalah jendela ajaib yang membuka pandangan dan pikiran kita ke seluruh penjuru dunia dengan pengetahuan yang luas dan tak terbatas. -Pustakawan Alam',
            'Belajarlah dengan tekun dari kesalahan dan pengalaman masa lalu yang telah terjadi, hiduplah sepenuhnya untuk menikmati momen indah di masa kini, dan rencanakan masa depanmu dengan penuh harapan dan bijak. -Filsuf Waktu',
            'Teman sejati yang baik dalam hidup ini sangat sulit untuk ditemukan, sulit juga untuk ditinggalkan ketika harus berpisah, dan rasanya tidak mungkin untuk dilupakan begitu saja sepanjang hidup. -Sahabat Hati',
            'Keluarga adalah fondasi utama tempat hidup dimulai dengan penuh kasih sayang yang tulus, dan cinta yang ada di dalamnya tidak akan pernah berakhir selamanya. -Bundadari Bijak',
            'Bersyukurlah dengan tulus atas segala sesuatu, sekecil apapun itu, yang sudah kamu miliki saat ini, dan teruslah berjuang tanpa henti untuk meraih apa yang masih kamu impikan di masa depan. -Pejuang Asa',
            'Kesuksesan besar yang sesungguhnya adalah hasil nyata yang dicapai dari kombinasi kerja keras yang konsisten, ketekunan yang luar biasa dalam menghadapi rintangan, dan dedikasi yang tinggi terhadap tujuan. -Pakar Karya',
            'Jangan pernah berhenti untuk belajar hal-hal baru dan mengembangkan dirimu, karena hidup adalah proses pembelajaran yang berkelanjutan dan tiada akhir. -Pembelajar Abadi',
            'Hiduplah setiap hari dengan penuh kejujuran dalam setiap perkataan dan perbuatanmu, karena kejujuran adalah mata uang paling berharga. -Nizamul Etika',
            'Pelajari untuk mencintai dirimu sendiri dengan segala kelebihan dan kekuranganmu, karena penerimaan diri adalah awal kebahagiaan. -Citra Diri',
            'Ulurkan tanganmu dengan tulus untuk membantu orang lain yang membutuhkan, karena berbagi kebaikan akan membawa kebahagiaan yang berlipat ganda. -Suka Menolong',
            'Pertahankan sikap positif dalam menghadapi segala situasi, baik suka maupun duka, karena pikiran positif akan menarik hal-hal baik ke dalam hidupmu. -Mentari Pagi',
            'Luangkan waktu sejenak setiap hari untuk merenung dan merasakan syukur atas berkah-berkah kecil maupun besar yang Tuhan berikan dalam hidupmu. -Hamba Syukur',
            'Nikmati setiap momen yang kamu jalani saat ini dengan penuh kesadaran, karena setiap momen adalah berharga dan tidak akan terulang kembali persis sama. -Penikmat Waktu',
            'Belajarlah untuk tidak terlalu khawatir secara berlebihan tentang hal-hal kecil yang sebenarnya tidak terlalu penting dalam gambaran besar kehidupan. -Tenang Jiwa',
            'Masa lalu yang sudah terjadi memang tidak bisa lagi diubah atau kembali, tetapi masa depanmu masih bisa sepenuhnya kamu bentuk sesuai keinginanmu mulai dari sekarang. -Perancang Takdir',
            'Setiap kesalahan yang kamu buat dalam hidup bukanlah kegagalan, melainkan sebuah pelajaran berharga yang akan membantumu tumbuh menjadi pribadi yang lebih baik dan kuat. -Evaluator Diri',
            'Jangan pernah merasa takut untuk mencoba sesuatu yang baru atau mengambil risiko hanya karena kamu takut akan kemungkinan kegagalan. -Pemberani Muda',
            'Percayalah sepenuhnya pada proses yang sedang kamu jalani untuk mencapai tujuan, meskipun terkadang terasa sulit dan melelahkan di tengah jalan. -Penganut Proses',
            'Konsisten dalam melakukan sesuatu secara terus-menerus, bahkan dalam hal-hal kecil, adalah kunci utama untuk mencapai hasil yang diinginkan dalam jangka panjang. -Rajin Konstan',
            'Disiplin diri yang kuat dan konsisten adalah fondasi penting yang akan membantumu membangun kekuatan mental dan mencapai tujuan-tujuan besarmu. -Adidaya Fokus',
            'Alihkan fokus perhatian dan energimu pada mencari solusi-solusi kreatif dan efektif daripada terus-menerus berkutat pada masalah yang dihadapi. -Pencari Solusi',
            'Bersabarlah dalam menjalani setiap proses kehidupan, hadapi tantangan dengan tenang, karena hasil yang baik membutuhkan waktu dan ketekunan yang gigih. -Sabar Menanti',
            'Hindari kebiasaan buruk membandingkan dirimu sendiri dengan orang lain, fokuslah pada perjalanan dan perkembangan dirimu sendiri secara unik. -Pribadi Unik',
            'Jalani kehidupanmu dengan caramu sendiri yang otentik, sesuai dengan nilai-nilai dan impianmu, jangan hanya meniru orang lain. -Arsitek Diri',
            'Beranikan dirimu untuk memiliki impian yang besar dan luar biasa yang mungkin dianggap mustahil atau tidak realistis oleh sebagian orang. -Pemimpi Agung',
            'Bertindaklah sekarang juga untuk memulai apa yang ingin kamu capai, jangan biarkan keraguan atau kemalasan membuatmu menunda-nunda lagi. -Aksi Cepat',
            'Hindari kebiasaan menunda-nunda pekerjaan atau tindakan yang seharusnya bisa kamu lakukan saat ini, selesaikan segera. -Anti Tunda',
            'Jangan lupakan untuk memberikan apresiasi dan merayakan setiap kemenangan kecil yang berhasil kamu raih dalam perjalananmu menuju tujuan besar. -Penyemangat Diri',
            'Jangan pernah berhenti mencoba lagi dan lagi meskipun kamu menghadapi kegagalan berulang kali, karena setiap kegagalan adalah langkah menuju sukses. -Tekun Berjuang',
            'Temukan sumber kebahagiaan sejati dan ketenangan batin dalam hal-hal sederhana yang seringkali luput dari perhatian di tengah hiruk pikuk kehidupan modern. -Penyuka Sederhana',
            'Bersikaplah ramah dan penuh kasih kepada semua orang yang kamu temui dalam hidupmu, sebarkan energi positif di sekitarmu. -Ramah Jiwa',
            'Belajarlah untuk memaafkan kesalahan orang lain yang telah menyakitimu, dan yang lebih penting lagi, maafkan dirimu sendiri atas kesalahan masa lalu. -Pemaaf Tulus',
            'Luangkan waktu sejenak setiap pagi untuk merasakan syukur yang mendalam atas berkah hari ini, kesehatan, dan kesempatan yang diberikan. -Pagi Syukur',
            'Kamu memiliki kekuatan yang luar biasa di dalam dirimu untuk menciptakan masa depan yang kamu impikan dengan tindakan dan keputusan yang kamu ambil hari ini. -Maestro Nasib',
            'Jangan takut untuk menunjukkan keunikanmu, bakatmu, dan menjadi berbeda dari orang lain di sekitarmu, itulah kekuatanmu. -Sang Unik',
            'Ingatlah selalu bahwa kamu sebenarnya jauh lebih kuat dan tangguh dalam menghadapi cobaan daripada yang mungkin kamu pikirkan selama ini. -Benteng Hati',
            'Jangan pernah menyerah pada harapan, betapapun gelapnya situasi, karena harapan adalah cahaya kecil yang menuntun di tengah kegelapan. -Pelita Harapan',
            'Ingatlah pepatah lama yang penuh makna, bahwa setiap awan gelap yang mendung pasti memiliki lapisan perak yang bersinar di baliknya. -Pelangi Kehidupan',
            'Percayalah dengan teguh dalam hatimu bahwa setelah badai besar dalam hidup pasti akan muncul pelangi yang indah dan penuh warna. -Pencerah Badai',
            'Ini bukanlah akhir dari segalanya yang kamu hadapi, ini hanyalah bagian dari perjalanan panjang kehidupanmu yang terus bergerak maju. -Narator Kehidupan',
            'Percayalah dengan keyakinan penuh bahwa hal-hal terbaik dalam hidupmu belum datang dan masih menunggu untuk kamu raih dengan usaha. -Penggapai Mimpi',
            'Teruslah berjuang dengan gigih dan pantang menyerah untuk mencapai impian dan tujuan-tujuan besarmu dalam hidup, jangan kendur. -Pendekar Tangguh',
            'Yakinlah dalam hatimu dengan seyakin-yakinnya bahwa kamu memiliki kemampuan yang dibutuhkan untuk melakukan apapun yang kamu impikan dan cita-citakan. -Keyakinan Diri',
            'Bangun kepercayaan yang kuat dan kokoh pada dirimu sendiri, karena kamu adalah orang yang paling tahu dan memahami potensi luar biasa yang kamu miliki. -Pembangun Jiwa',
            'Ingatlah selalu bahwa kamu tidak sendirian dalam menghadapi tantangan hidup ini, ada banyak orang yang peduli padamu dan siap mendukung. -Solidaritas Insan',
            'Pada akhirnya, segalanya akan menjadi baik-baik saja pada waktunya, jadi jangan kehilangan harapan dan teruslah berusaha. -Optimis Abadi',
            'Jika suatu hal belum berakhir dengan hasil yang baik, itu hanya berarti bahwa perjalanan menuju hasil terbaik itu belum benar-benar usai, teruslah melangkah. -Pemburu Akhir',
            'Harapan adalah sesuatu yang sangat baik dan berharga, mungkin hal terbaik dari semuanya yang bisa dimiliki manusia, dan hal baik semacam itu tidak akan pernah benar-benar mati. -Stephen King',
            'Tidak ada hal di dunia ini yang tidak bisa kamu lakukan atau capai jika kamu memiliki pola pikir dan keyakinan yang benar serta kuat di dalam dirimu. -Arif Mindset',
            'Rahasia yang paling penting untuk mulai bergerak maju dalam hidup dan meninggalkan kebiasaan lama adalah dengan mengambil langkah pertama untuk benar-benar memulai tindakan nyata. -Inisiator Aksi',
        ];
    }
}